const audioInput=document.querySelector('#audio-input');const dropZone=document.querySelector('#drop-zone');const fileInfo=document.querySelector('#file-info');const scriptInput=document.querySelector('#script-input');const lineCount=document.querySelector('#line-count');const syncBtn=document.querySelector('#sync-btn');const homeView=document.querySelector('#home-view');const resultView=document.querySelector('#result-view');const table=document.querySelector('#subtitle-table');const audioState={file:null,duration:0};let subtitles=[];
function lines(){return scriptInput.value.split(/\n/).map(s=>s.trim()).filter(Boolean)}
function update(){const n=lines().length;lineCount.textContent=n;syncBtn.disabled=!audioState.file||!n}
function formatTime(seconds){seconds=Math.max(0,seconds);const h=Math.floor(seconds/3600);const m=Math.floor(seconds%3600/60);const s=Math.floor(seconds%60);const ms=Math.round((seconds-Math.floor(seconds))*1000);return [String(h).padStart(2,'0'),String(m).padStart(2,'0'),String(s).padStart(2,'0')].join(':')+','+String(ms).padStart(3,'0')}
function parseTime(value){const match=value.match(/^(\d{2}):(\d{2}):(\d{2}),(\d{3})$/);return match?Number(match[1])*3600+Number(match[2])*60+Number(match[3])+Number(match[4])/1000:null}
function setFile(file){if(!file)return;if(!/\.(mp3|wav|m4a)$/i.test(file.name)){showToast('Selecciona un archivo MP3, WAV o M4A');return}audioState.file=file;fileInfo.textContent=`✓ ${file.name}`;fileInfo.classList.remove('hidden');const url=URL.createObjectURL(file);const audio=new Audio();audio.src=url;audio.addEventListener('loadedmetadata',()=>{audioState.duration=audio.duration||0;URL.revokeObjectURL(url)});update()}
audioInput.addEventListener('change',e=>setFile(e.target.files[0]));['dragenter','dragover'].forEach(e=>dropZone.addEventListener(e,ev=>{ev.preventDefault();dropZone.classList.add('dragging')}));['dragleave','drop'].forEach(e=>dropZone.addEventListener(e,ev=>{ev.preventDefault();dropZone.classList.remove('dragging')}));dropZone.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));scriptInput.addEventListener('input',update);
function createSubtitles(){const source=lines();const totalChars=source.reduce((a,s)=>a+s.length,0);const duration=audioState.duration||Math.max(3,source.length*3);let cursor=0;subtitles=source.map((text,i)=>{const share=text.length/totalChars;const gap=i===source.length-1?0:.12;const span=Math.max(1.1,duration*share-gap);const start=cursor;const end=Math.min(duration,start+span);cursor=end+gap;return{number:i+1,start:formatTime(start),end:formatTime(end),text}});render();document.querySelector('#result-file').textContent=audioState.file.name;document.querySelector('#result-count').textContent=`${subtitles.length} subtítulos`;homeView.classList.add('hidden');resultView.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function render(){table.innerHTML=subtitles.map((s,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td><input class="time-input" data-index="${i}" value="${s.start} --> ${s.end}" aria-label="Tiempo del subtítulo ${i+1}"></td><td class="text-cell">${escapeHtml(s.text)}</td></tr>`).join('');table.querySelectorAll('.time-input').forEach(input=>input.addEventListener('change',()=>{const pair=input.value.split('-->').map(x=>x.trim());if(pair.length===2&&parseTime(pair[0])!==null&&parseTime(pair[1])!==null){subtitles[input.dataset.index].start=pair[0];subtitles[input.dataset.index].end=pair[1]}else{input.value=`${subtitles[input.dataset.index].start} --> ${subtitles[input.dataset.index].end}`;showToast('Formato inválido. Usa 00:00:00,000 --> 00:00:00,000')}}))}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function getSrt(){return subtitles.map(s=>`${s.number}\n${s.start} --> ${s.end}\n${s.text}`).join('\n\n')+'\n'}function showToast(text){const toast=document.querySelector('#toast');toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2500)}
syncBtn.addEventListener('click',createSubtitles);document.querySelector('#back-btn').addEventListener('click',()=>{resultView.classList.add('hidden');homeView.classList.remove('hidden')});document.querySelector('#download-btn').addEventListener('click',()=>{const blob=new Blob([getSrt()],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(audioState.file?.name.replace(/\.[^.]+$/,'')||'subtitulos')+'.srt';a.click();URL.revokeObjectURL(a.href);showToast('Archivo SRT descargado')});document.querySelector('#copy-btn').addEventListener('click',async()=>{await navigator.clipboard.writeText(getSrt());showToast('SRT copiado al portapapeles')});
