const express=require('express');const {chromium}=require('playwright');const path=require('path');
const PORT=Number(process.env.PORT||8787),FLOW_URL='https://flow.google.com/',CDP_URL=process.env.CDP_URL||'http://127.0.0.1:9222';const app=express();
app.use((req,res,next)=>{res.header('Access-Control-Allow-Origin','*');res.header('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.header('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS')return res.sendStatus(204);next()});app.use(express.json({limit:'5mb'}));
let queue=[],running=false,status={state:'idle',message:'Automatizador listo',batch:0};let browser,page;
app.get('/health',(req,res)=>res.json({ok:true,status}));app.get('/status',(req,res)=>res.json({ok:true,status,queued:queue.length}));app.post('/enqueue',(req,res)=>{if(!Array.isArray(req.body.batch)||!req.body.batch.length)return res.status(400).json({error:'batch requerido'});queue.push(req.body);res.json({ok:true,queued:queue.length});if(!running)run()});app.post('/stop',(req,res)=>{running=false;queue=[];status={state:'stopped',message:'Detenido',batch:status.batch};res.json({ok:true})});
async function ensurePage(){if(!browser){try{browser=await chromium.connectOverCDP(CDP_URL)}catch(e){throw new Error('No se pudo conectar a tu Chrome. Cierra Chrome y ejecuta abrir-chrome-perfil.bat antes de enviar el lote.')}}const pages=browser.contexts().flatMap(c=>c.pages());page=pages.find(p=>/flow\.google\.com/i.test(p.url()))||pages[0]||await browser.contexts()[0].newPage();if(!/flow\.google\.com/i.test(page.url()))await page.goto(FLOW_URL,{waitUntil:'domcontentloaded'});return page}
async function pasteIntoFlow(text){await page.bringToFront();const target=page.locator('textarea,[contenteditable="true"]').first();await target.waitFor({state:'visible',timeout:20000});await target.click();await page.keyboard.insertText(text)}
async function clickGenerate(){for(const label of ['Generate','Create','Generar','Crear','Generate video','Crear vídeo']){const b=page.getByRole('button',{name:new RegExp(label,'i')}).first();if(await b.count()&&await b.isVisible().catch(()=>false)){await b.click();return true}}return false}
async function run(){running=true;while(queue.length&&running){const item=queue.shift();status={state:'opening',message:'Conectando con tu perfil de Chrome',batch:item.batchNumber||status.batch+1};try{await ensurePage();status={state:'sending',message:'Pegando lote en Google Flow',batch:status.batch};await pasteIntoFlow(item.batch.join('\n\n'));const clicked=await clickGenerate();status={state:clicked?'waiting':'needs_action',message:clicked?'Generación iniciada; esperando':'No encontré el botón Generar; revísalo manualmente',batch:status.batch};if(clicked)await page.waitForTimeout(Number(process.env.FLOW_WAIT_MS||10000));status={state:'done',message:'Lote terminado; listo para el siguiente',batch:status.batch}}catch(e){status={state:'error',message:e.message,batch:status.batch}}}running=false;if(status.state!=='error')status.state='idle'}app.listen(PORT,'127.0.0.1',()=>console.log(`SRTSync Flow Automator escuchando en http://127.0.0.1:${PORT}`));
