const express=require('express');const {chromium}=require('playwright');const fs=require('fs');const path=require('path');
const PORT=Number(process.env.PORT||8787),FLOW_URL=process.env.FLOW_URL||'https://labs.google/fx/tools/flow',PROFILE=process.env.FLOW_PROFILE||path.join(__dirname,'.flow-profile');const app=express();app.use(express.json({limit:'5mb'}));let queue=[],running=false,status={state:'idle',message:'Automatizador listo',batch:0};let browser,page;
app.get('/health',(req,res)=>res.json({ok:true,status}));app.post('/enqueue',(req,res)=>{if(!Array.isArray(req.body.batch)||!req.body.batch.length)return res.status(400).json({error:'batch requerido'});queue.push(req.body);res.json({ok:true,queued:queue.length});if(!running)run()});app.post('/stop',(req,res)=>{running=false;queue=[];status={state:'stopped',message:'Detenido',batch:status.batch};res.json({ok:true})});app.get('/status',(req,res)=>res.json({ok:true,status,queued:queue.length}));
async function ensurePage(){if(!browser)browser=await chromium.launchPersistentContext(PROFILE,{headless:false,viewport:{width:1440,height:900},permissions:['clipboard-read','clipboard-write']});page=browser.pages()[0]||await browser.newPage();if(!page.url().includes('labs.google'))await page.goto(FLOW_URL,{waitUntil:'domcontentloaded'});return page}
async function pasteIntoFlow(text){await page.bringToFront();await page.evaluate(async t=>navigator.clipboard.writeText(t),text);const target=page.locator('textarea,[contenteditable="true"]').first();await target.waitFor({state:'visible',timeout:15000});await target.click();await page.keyboard.press(process.platform==='darwin'?'Meta+V':'Control+V');}
async function clickGenerate(){const labels=['Generate','Create','Generar','Crear','Generate video','Crear vídeo'];for(const label of labels){const b=page.getByRole('button',{name:new RegExp(label,'i')}).first();if(await b.count()&&await b.isVisible().catch(()=>false)){await b.click();return true}}return false}
async function waitUntilDone(){await page.waitForTimeout(Number(process.env.FLOW_WAIT_MS||10000));}
async function run(){running=true;while(queue.length&&running){const item=queue.shift();status={state:'opening',message:'Abriendo Google Flow; inicia sesión si es necesario',batch:item.batchNumber||status.batch+1};try{await ensurePage();status={state:'sending',message:'Pegando lote en Google Flow',batch:status.batch};await pasteIntoFlow(item.batch.join('\n\n'));const clicked=await clickGenerate();status={state:clicked?'waiting':'needs_action',message:clicked?'Generación iniciada; esperando':'No encontré el botón Generar: revisa Flow y pulsa manualmente',batch:status.batch};if(clicked)await waitUntilDone();status={state:'done',message:'Lote terminado; listo para el siguiente',batch:status.batch}}catch(e){status={state:'error',message:e.message,batch:status.batch}}}running=false;if(status.state!=='error')status.state='idle'}
app.listen(PORT,'127.0.0.1',()=>console.log(`SRTSync Flow Automator escuchando en http://127.0.0.1:${PORT}`));
